### ISSUE TITLE
Can't fix error from mod browser 

### ISSUE THREAD

**Issue by XenonZe** [Anuken/MindustryMods#20]
I know this is the wrong place, but it relates to the mod browser. I was installing a bunch from there and all was fine until it now no longer loads. Like it will give the "uh oh" window. I've removed every trace of the mods I can find from my install location, as well as checking appdata/roaming, despite there being zero trace of any additional mod folder. Where does it keep mods? I removed all the mods I could find but there seems to be some source folder I cannot find.
----
java.lang.IllegalArgumentException: scaleX cannot be 0.
	at arc.graphics.g2d.Font$FontData.setScale(Font.java:943)
	at arc.scene.ui.Label.scaleAndComputePrefSize(Label.java:128)
	at arc.scene.ui.Label.getPrefWidth(Label.java:229)
	at arc.scene.ui.layout.Cell.prefWidth(Cell.java:118)
	at arc.scene.ui.layout.Table.computeSize(Table.java:924)
	at arc.scene.ui.layout.Table.getPrefWidth(Table.java:664)
	at arc.scene.ui.layout.WidgetGroup.pack(WidgetGroup.java:116)
	at UnitInfo.ui.UnitDisplay$1.lambda$new$5(UnitDisplay.java:80)
	at arc.scene.ui.layout.Table.<init>(Table.java:75)
	at UnitInfo.ui.UnitDisplay$1.lambda$new$6(UnitDisplay.java:70)
	at arc.scene.ui.layout.Table.<init>(Table.java:75)
	at UnitInfo.ui.UnitDisplay$1.<init>(UnitDisplay.java:69)
	at UnitInfo.ui.UnitDisplay.lambda$new$13(UnitDisplay.java:56)
	at arc.scene.ui.layout.Table.table(Table.java:275)
	at arc.scene.ui.layout.Table.table(Table.java:269)
	at UnitInfo.ui.UnitDisplay.lambda$new$17(UnitDisplay.java:54)
	at arc.scene.ui.layout.Table.<init>(Table.java:70)
	at UnitInfo.ui.UnitDisplay.<init>(UnitDisplay.java:53)
	at UnitInfo.core.HudUi.lambda$addTable$62(HudUi.java:319)
	at arc.scene.ui.layout.Table.<init>(Table.java:75)
	at UnitInfo.core.HudUi.addTable(HudUi.java:291)
	at UnitInfo.core.Main.lambda$init$1(Main.java:42)
	at mindustry.ClientLauncher.lambda$update$11(ClientLauncher.java:159)
	at arc.Events.lambda$fireWrap$3(Events.java:37)
	at arc.struct.Seq.each(Seq.java:199)
	at arc.Events.fireWrap(Events.java:36)
	at mindustry.ClientLauncher.update(ClientLauncher.java:157)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:166)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:154)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:45)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:39)

**Comment by Anuken** [comment]
This has nothing to do with the mod browser or this repository, it's a bug in the UnitInfo mod. Make sure all your mod directories are empty and that you are unsubscribed from all mods if on Steam.
